# -*- coding: utf-8 -*-
"""exercicio_20240208.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ZT0Ak2869ZvHrRrohmbAgsxCURlT5cT

1. Leia dois números, faça a soma e apresente caso seja maior que 15.
"""

n1 = float(input("Entre com o primeiro numero: "))
n2 = float(input("Entre com o segundo numero: "))
soma = n1 + n2
if soma > 15:
  print(soma)

"""2. Faça um programa que recebendo um valor inteiro, informe se o número é positivo, negativo ou neutro.

"""

n = int(input("Entre com o primeiro numero:"))

if n < 0:
  print("negativo")
elif n > 0:
  print("positivo")
else:
  print("neutro")

"""3. Leia a idade e informe se a pessoa é maior ou menor de idade"""

idade = int(input("Entre com a idade: "))
if idade<18:
  print("Voce é menor de idade")
else:
  print("Voce é maior de idade")

""" 4. Faça um programa que pergunte a temperatura atual para o usuário e mostre uma
mensagem na tela dizendo se está “quente”, “frio” ou “agradável”.
"""

temperatura = float(input("Entre com a temperatura: "))
if temperatura < 15.0:
  print("Hoje esta frio")
elif temperatura < 25.0:
  print("Hoje esta agradavel")
else:
  print("Hoje esta quente")

"""5. Faça um programa em linguagem Python que leia dois números inteiros e informe se estes são iguais ou diferentes.

"""

n1 = int(input("informe o primeiro numero: "))
n2= int(input("informe o segundo numero: "))
if n1==n2:
  print("Os numeros sáo iguais")
else:
  print("Os numeros sáo diferentes")

"""6. Escreva um programa que verifique a validade de uma senha fornecida pelo
usuário. A senha válida é o número 1234. Devem ser impressas as seguintes
mensagens:
. ACESSO PERMITIDO caso a senha seja válida.
. ACESSO NEGADO caso a senha seja inválida.
"""

senha = int(input("Informe sua senha: "))
if senha==1234:
  print("Acesso permitido")
else:
  print("Acesso negado")

"""7. Ler duas notas de um aluno, efetuar a média aritmética e, se a média for maior ou igual a 7, informar que o aluno foi aprovado; se a média for maior ou igual a 5 mas menor do que 7, informar que o aluno está de exame; se a média for menor do que 5 informar que o aluno foi reprovado.

"""

nota1 = float(input("informe o primeira nota: "))
nota2= float(input("informe o segunda nota: "))
media = (nota1+nota2)/2
if media>7:
  print("Aluno aprovado")
elif media>=5 and media<=7:
  print("Aluno esta de exame")
else:
  print("Aluno reprovado")

"""8. Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os gols de cada time) e informe se o resultado foi um empate, se a vitória foi do primeiro time ou do segundo time.

"""

time1 = int(input("informe os gols do time 1: "))
time2 = int(input("informe os gols do time 2: "))
if time1>time2:
  print("Time 1 é o vencedor")
elif time2>time1:
  print("Time 2 é o vencedor")
else:
  print("Time 1 e Time2 empataram")

"""9. Faça um Programa que pergunte em que turno você estuda. Peça para digitar Mmatutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa
Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.

"""

periodo = input("Qual o periodo que voce estuda: (M)atutino, (V)espertino,(N)oturno: ")
if periodo=="M":
  print("Bom dia")
elif periodo=="V":
  print("Boa tarde")
elif periodo=="N":
  print("Boa Noite")
else:
  print("opcao invalida!")

"""10. Faça um programa que solicite ao usuário sua idade, depois disso, exiba a
classificação etária de acordo com as faixas de valores:
 Criança para 0 até 11 anos;
 Adolescente para 12 até 18 anos;
 Jovem para 19 até 24 anos;
 Adulto para 25 até 40 anos;
 Meia Idade para 41 até 60 anos;
 Idoso acima de 60 anos.
"""

idade = int(input("Entre com a idade: "))
if idade>=0 and idade <=11:
  print("Voce é uma crianca")
elif idade>=12 and idade <=18:
  print("Voce é um adolecente")
elif idade>=19 and idade <=24:
  print("Voce é um jovem")
elif idade>=25 and idade <=40:
  print("Voce é um adulto")
elif idade>=41 and idade <=60:
  print("Voce é um adulto de meia idade")
elif idade>60:
  print("Voce é um idoso")
else:
  print("idade invalida")

"""11. As Organizações Tabajara resolveram dar um aumento de salário aos seus
colaboradores e lhe contrataram para desenvolver o programa que calculará os
reajustes. Faça um programa que recebe o salário de um colaborador e o reajuste
segundo o seguinte critério, baseado no salário atual:
 salários até R$ 280,00 (incluindo) : aumento de 20%
 salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
 salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
 salários de R$ 1500,00 em diante : aumento de 5%
Após o aumento ser realizado, informe na tela:
 o salário antes do reajuste;
 o percentual de aumento aplicado;
 o valor do aumento;
 o novo salário, após o aumento.
"""

salario = float(input("Informe o salario: "))
if salario<=280.00:
  percentual = 20
  reajuste = (salario * percentual) / 100
  novo_salario = salario + reajuste
elif salario > 280.00 and salario <= 700.00:
  percentual = 15
  reajuste = (salario * percentual) / 100
  novo_salario = salario + reajuste
elif salario > 700.00 and salario <= 1500.00:
  percentual = 10
  reajuste = (salario * percentual) / 100
  novo_salario = salario + reajuste
else:
  percentual = 5
  reajuste = (salario * percentual) / 100
  novo_salario = salario + reajuste

print(f"Seu salario era {salario} com reajuste de {percentual}% R$ {reajuste} seu salario passou para R$ {novo_salario}")

"""12. Faça um Programa que leia um número e exiba o dia correspondente da semana.
(1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.

"""

dia_semana=["Domingo","Segunda","Terca","Quarta","Quinta","Sexta","Sabado"]
num = int(input("Informe um numero entre (1-7)"))
if num<1 or num>7:
    print("Valor invalido")
else:
  print(dia_semana[num-1])

"""13. . Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de Fahrenheit para Celsius ou de Celsius para Fahrenheit, e que, a partir da resposta do usuário, faça a devida conversão."""

opcao = int(input("Escola uma opcao (1) Fahrenheit para Celsius, (2) Celsius para Fahrenheit"))
valor = float(input("Entre com o valor: "))
if opcao == 1:
  valor_convertido = (valor - 32 ) / 1.8
  print("O valor de {valor} convertido para Celsius é: {valor_convertido}")
elif opcao == 2
  valor_convertido = (valor * 32) + 1.8
  print("O valor de {valor} convertido para Fahrenheit é: {valor_convertido}")
else:
  print("opcao invalida")

"""14. Faça um programa que receba a idade de uma pessoa e imprima sua condição
(obrigatória, optativa ou proibida), em relação ao ato de votar, conforme
apresentado abaixo:
 Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
 Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar
(optativo);
 Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar
(obrigatório);
 Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).
"""

idade = int(input("Entre com a idade: "))
if idade<16:
  print("Seu voto é proibido")
elif idade<18 or idade>65:
  print("Seu voto é opcional")
else:
  print("Seu voto é obrigatorio")

"""15. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As
perguntas são:
 “Telefonou para a vítima? “
 “Esteve no local do crime?”
 “Mora perto da vítima? “
 “Devia para a vítima? “
 “Já trabalhou com a vítima? “ O programa deve no final emitir uma classificação sobre a participação da pessoa
no crime. Se a pessoa responder positivamente a 2 questões ela deve ser
classificada como “Suspeita”, entre 3 e 4 como “Cúmplice” e 5 como “Assassino“.
Caso contrário, ele será classificado como “Inocente“.
"""

resposta1 = input("Telefonou para a vítima? (sim/Nao)")
resposta2 = input("Esteve no local do crime? (sim/Nao)")
resposta3 = input("Mora perto da vítima? (sim/Nao)")
resposta4 = input("Devia para a vítima? (sim/Nao) ")
resposta5 = input("Já trabalhou com a vítima? (sim/Nao) ")
contador = 0
if resposta1=="sim": contador+=1
if resposta2=="sim": contador+=1
if resposta3=="sim": contador+=1
if resposta4=="sim": contador+=1
if resposta5=="sim": contador+=1

if contador==5:
  print("Assasino")
elif contador>=3 and contador<=4:
  print("Cumplice")
elif contador ==2:
  print("Suspeito")
else:
  print("Inocente")

"""16. Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

preco1 = input("Informe o preco 1: ")
preco2 = input("Informe o preco 2: ")
preco3 = input("Informe o preco 3: ")
if preco1<preco2:
  if preco3<preco1:
    print(preco3)
  else:
    print(preco1)
elif preco3<preco2:
  print(preco3)
else:
  print(preco2)